#!/bin/bash
# delete all specific files generated by campaigns which did not complete

#go to current file directory
cd "${0%/*}"

find config -regex "config/temp[0-9]+\..*\.yaml" -delete
rm -r ns3_experiments/runs/run_loaded*
rm -r satellite_networks_state/gen_data/*

find satellite_networks_state/input_data/ -regex "satellite_networks_state/input_data/os_.*_[0-9]+\.csv" -delete