experiences: #classer par ordre
  graine: [0]
  constellation: [ tas_700 ] # name will be inflated from files chosen in this directory
  duree: [8] #en s
  pas: [2000] #en ms
  isls: [ isls_plus_grid ]
  deteriorISL: [ { sel: topUtil10, errRate: 0.1 } ]
  sol: [ users_and_main_stations ]
  nb-UEs-sol: [ 10 ]
  algo: [ "algorithm_free_one_only_over_isls" ]
  threads: [4 ]
  debit_isl: [ 10]


info-sauvegarde:
  strdate: '%Y-%m-%d-%H%M'
  destdir: "sauvegardes/svgde_{strdate}_{graine}"
  sources:
    satgenpy_analysis/data: "{constellation}_{isls}_{sol}_{algo}"
    "satellite_networks_state/gen_data/{constellation}_{isls}_{sol}_{algo}": ground_stations.txt
    ns3_experiments/runs: run.*
  #currinfo: currlog #sinon commenter ce champs
  execution: graine # sauvegarder après chaque graine, les autres paramètres de l'expérience étant changés
