experienceBursty: #classer par ordre
  graine: [0]
  constellation: [ tas_700 ] # name will be inflated from files chosen in this directory
  duree: [8] #en s
  pas: [2000] #en ms
  isls: [ isls_plus_grid ]
  # examples of errModel 
  #      "gilbertElliottMdl-brstRate:0.1-brstSize:3.2" "brstErrMdl-rate:0.1-size:5"  
  #      "brstErrMdl-brstRate:0.01-brstSize:5"
  deteriorISL: [ { sel: topUtil10, errModel: "gilbertElliottMdl-brstRate:0.01-brstSize:5" }, {}] # { sel: topUtil10, errModel: "brstErrMdl-brstRate:0.01-brstSize:5" } ] #{ sel: topUtil10, errModel: "gilbertElliottMdl-brstRate:0.01-brstSize:5" } ] # "gilbertElliottMdl-brstRate:0.01-brstSize:10" "recvErrRate:0.1"
  sol: [ users_and_main_stations ]
  nb-UEs-sol: [ 10 ]
  algo: [ "algorithm_free_one_only_over_isls" ]
  threads: [4 ]
  debit_isl: [ 10, 2 ]
  protocoles: [ {'nom':"udp", "metadata":"expInterPacket"} ]  # ["udp", "tcp"]


info-sauvegarde:
  strdate: '%Y-%m-%d-%H%M'
  campagnedir: "sauvegardes/{nom_campagne}"
  expedir: "svgde_{strdate}_{graine}"
  sources:
    "satgenpy_analysis/data/{constellation}_{isls}_{sol}_{algo}/{pas}ms_for_{duree}s/": manual
    "satellite_networks_state/gen_data/{constellation}_{isls}_{sol}_{algo}": ground_stations.txt
    ns3_experiments/runs: "run_loaded_tm_pairing_{debit_isl}_Mbps_for_{duree}s_with_.*_{algo}"
    config: courante.yaml
  #currinfo: currlog #pour savoir où on en est, si lancé en arrière-plan

actions: #[]
  - noeuds
  - commodites
  - routes
  - "analyse theorique"
  - "casse liens sat"  # attention, l'analyse théorique doit être juste sinon les liens isl desactives seront aleatoires
  - simulation