experiences: #classer par ordre
  graine: [0]
  constellation: [ tas_700 ] # name will be inflated from files chosen in this directory
  duree: [8] #en s
  pas: [2000] #en ms
  isls: [ isls_plus_grid ]
  deteriorISL: [ { sel: topUtil10, errRate: 0.1 } ]
  sol: [ users_and_main_stations ]
  algo: [ "algorithm_free_one_only_over_isls" ]
  threads: [4 ]
  debit_isl: [ 10]


info-sauvegarde:
  strdate: '%Y-%m-%d-%H%M'
  destdir: "sauvegardes/svgde_{strdate}_{graine}"
  sources: 
    ns3_experiments/traffic_matrix_load/runs: run.*
    #satgenpy_analysis: data 
  #currinfo: currlog #sinon commenter ce champs
  execution: graine # sauvegarder après chaque graine, les autres paramètres de l'expérience étant changés
