algo: algorithm_free_one_only_over_isls
constellation: tas_700
debit_isl: 10
deteriorISL:
  errRate: 0.1
  sel: topUtil10
duree: 8
graine: 0
isls: isls_plus_grid
nb-UEs-sol: 10
pas: 2000
sol: users_and_main_stations
threads: 4
