# The MIT License (MIT)
#
# Copyright (c) 2020 ETH Zurich
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# GENERATION CONSTANTS

BASE_NAME: "kuiper_630"
NICE_NAME: "Kuiper-630"

################################################################
# The below constants are taken from Kuiper's FCC filing as below:
# [1]: https://www.itu.int/ITU-R/space/asreceived/Publication/DisplayPublication/8716
################################################################

# KUIPER 630
#TODO: consider shell as an object
satellite: {}
  #just for buffer conf
ECCENTRICITY: 0.0000001  # Circular orbits are zero, but pyephem does not permit 0, so lowest possible value
ARG_OF_PERIGEE_DEGREE: 0.0
PHASE_DIFF: True

ALTITUDE_M: 630000  # Altitude ~630 km
NUM_ORBS: 34
NUM_SATS_PER_ORB: 34
INCLINATION_DEGREE: 51.9

ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE: 75
# orbites circulaires, périgée confondu avec le noeud ascendant à l'équateur, lorsque l'anomalie atteint 90°, le satellite est à sa latitude maximale. 
# lorsque l'anomalie dépasse ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE, les isl adjacents sont désactivés
# Par symétrie centrale, les ISL sont désactivés lorsque l'anomalie et comprise entre ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE et 180-ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE
# ou entre -ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE et ISL_POLAR_DESACTIVATION_ANOMALY_DEGREE-180
# Todo: différencier désactivations à droite et à gauche

#same names as in debit_gsl
TYPES_OBJETS_SOL: ['gateway', 'ue', 'server'] #/!\ /!\ /!\ NE PAS CHANGER L'ORDRE /!\ /!\ /!\ ou modifier l'écriture des interfaces et/ou la génération des objets sol

#interface allocation: lo, isl, gsl, finally terrestrial links
#a change in interface configuration must be reflected in the system configuration (topology-satellite-network files)

gateway: 
  positions: os_Lille # ground_stations_cities_sorted_by_estimated_2025_pop_top_100_basic: 100 biggest cities, Hypatia base file; ground_stations_cities_by_estimated_2025_pop_300k_UN: +300k cities, United Nations estimate
  nombre: 1 #random, give IDs and place them, or set it in config?
  minElevation: 20 #degrees above horizon

ue:
  positions: os_1villes_kuiper630 #villesGlobe_kuiper630 #os_1villes_kuiper630 #randomGlobe_kuiper630 : randomGlobe= universel sur Terre, _{constellation_file_name.replace('_', '')} = à portée de la constellation . villesGlobe: Kent distribution around big cities
  minElevation: 20 #degrees above horizon
  nombre: $config/nb-UEs-sol #voir dans config
  estimDelai: $config/estimDelai/extremite #special for  extremities of the connection.
  
server:
  positions: os_Lille
  nombre: 1
  estimDelai: $config/estimDelai/extremite #special for  extremities of the connection.


LINKS:
    - ["isl", {"satellite": { 'DataRate': "DataRate~$config/debit-if-isl/Mbps"}}, {"limiteDist": True, "detraque": $config/deteriorISL, "estimDelai": $config/estimDelai/isl }] #interfaces between satellites, to be used together with the "plus grid"
    - ["gsl", { "satellite": { 'DataRate': "DataRate~$config/debit-if-gsl/satellite/Mbps"}, "ue": { 'DataRate': "DataRate~$config/debit-if-gsl/ue/Mbps" }}, {"limiteDist": True, "penalite_s": 10, "estimDelai": $config/estimDelai/gsl }] # although the ue has only 1 interface, it only makes 1 connection, so it does not need to choose the closest sat
    - ["gsl", { "satellite": { 'DataRate': "DataRate~$config/debit-if-gsl/satellite/Mbps"}, "gateway": { 'DataRate': "DataRate~$config/debit-if-gsl/gateway/Mbps", maxSatellites: 5 }}, {"limiteDist": True, "penalite_s": 10, "estimDelai": $config/estimDelai/isl }] # in reality, the gateway has a limited number of interfaces, and connects many users. To maximize bandwidth (not implemented here), we select the 5 closest satellites
    # GSL
    - ["tl", { "server": { 'DataRate': "DataRate~$config/debit-if-gsl/gateway/Mbps", $config/srvTrafficControl}, "gateway": { 'DataRate': "DataRate~$config/debit-if-gsl/gateway/Mbps"}}, {"Delay": "Time~5ms", "estimDelai": 5}] # gateway
    #- "tl", {agg_max_bandwidth: 1}, 1 #one-one, with 1 server


ENDPOINTS:
  - ue # Its datarate is used by default as reference for setting up commodities, datarate...
  - server
