# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('round-robin', ['core', 'network'])
    module.source = [
        "model/ipv4-dst-packet-filter.cc",
        "model/rr-queue-disc.cc",
        "model/rr-fqueue-disc.cc",
        "model/itbf-queue-disc.cc"
    ]

    module_test = bld.create_ns3_module_test_library('round-robin')
    module_test.source = [
        'test/rr-queue-disc-test-suite.cc',
        'test/rr-fqueue-disc-test-suite.cc',
    ]

    headers = bld(features='ns3header')
    headers.module = 'round-robin'
    headers.source = [
        "model/ipv4-dst-packet-filter.h",
        "model/rr-queue-disc.h",
        "model/rr-fqueue-disc.h",
        "model/itbf-queue-disc.h"
    ]

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    #bld.ns3_python_bindings()
