# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('contrib-utils', ['core', 'network'])
    module.source = [
        "model/specie.cc",
        "model/states-error-model.cc",
        "model/trace-journal.cc",
        "helper/device-factory-helper.cc"
    ]

    #module_test = bld.create_ns3_module_test_library('round-robin')
    #module_test.source = ['test/rr-queue-disc-test-suite.cc',]

    headers = bld(features='ns3header')
    headers.module = 'contrib-utils'
    headers.source = [
        "model/states-error-model.h",
        "model/specie.h",
        "model/trace-journal.h",
        "helper/device-factory-helper.h"
    ]

    #if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    #bld.ns3_python_bindings()
